### ISSUE TITLE
Why are you not adding the biblio references to specref.org?

### ISSUE THREAD

**Issue by tobie** [w3c/webpayments-ig#24]
Hi,

Curious as to why you're maintaining an IG-specific bibliography instead of contributing to the Specref project?

**Comment by msporny** [comment]
No idea, @halindrome ?

**Comment by halindrome** [comment]
We aren't. It's just for things that are in development and not yet
published at all so references will resolve.

**Comment by halindrome** [comment]
To be clear I assume you are talking about the biblio structure for
localBiblio.  Right?

**Comment by tobie** [comment]
I was referring to this: https://github.com/w3c/webpayments-ig/blob/master/latest/common/biblio.js

**Comment by tobie** [comment]
A bunch of references here are marked as "not available from Specref", e.g.: [GTK](https://github.com/w3c/webpayments-ig/blob/master/latest/common/biblio.js#L68).

**Comment by halindrome** [comment]
Sure. That's just a place to capture references that are not yet in
specref. New documents.

**Comment by tobie** [comment]
So my question basically is: what prevents you from adding those directly to specref? Specref auto-deploys on merge so the process should be super fast and seamless. Do you not have commit rights?

**Comment by halindrome** [comment]
I was instructed in no uncertain terms to never add anything to specref /
biblio when it is a nascent thing that will be automatically integrated
once there is a publication.  Got slapped down pretty hard, actually.
That's why.  PFWG does the same thing.  localBiblio definitions for things
that are in development so that the evolving specs point to one another
instead of to older versions that specref might know about.

Note that neither of these groups uses echidna at this point.  There is no
auto-publication going on, so it is only after an FPWD that an entry will
even show up in specref.  And once it is, it is largely automatically out
of date.

What we do in PFWG is have some conditional code in biblio.js that
magically points to the correct version depending on the status of the
document (ED, WD, etc.) so that when we go through the publication tool
chain the references to our own dependent specs remain correct.

On Fri, Jul 10, 2015 at 9:56 AM, Tobie Langel notifications@github.com
wrote:

> So my question basically is: what prevents you from adding those directly
> to specref? Specref auto-deploys on merge so the process should be super
> fast and seamless. Do you not have commit rights?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/webpayments-ig/issues/24#issuecomment-120428994.

## 

Shane McCarron
halindrome@gmail.com

**Comment by tobie** [comment]
Sorry for the bad experience you've had contributing to Specref in the past.

I'd really like to find a solution to this issue (unless using Echidna solves this, in which case let's just wait until everyone switches).

I'll email you to setup a call.

**Comment by erfekkes** [comment]
I have replaced the glossary list in terms.html with definitions for the Use Cases / Capabilities / Charter documents. The terms used are pulled from earlier WPAY glossary documents with some terms added from sources like the Payment Services Directive [PSD2] and European Central Bank [ECB] glossary.
It is the intention of the Web Payments Interest Group to moderate the contents of the Glossary in this terms.html file.
Process suggestions are very welcome!

**Comment by tobie** [comment]
Added the missing specs to Specref in https://github.com/tobie/specref/commit/a947cf3628360ee89746f6f339699e2ecc2d95c7.

@erfekkes: FWIW, I'm unsure where PSD2 and ECB are referenced. You're welcome to [add them to Specref](https://github.com/tobie/specref#manual-changes). :)
