### ISSUE TITLE
VCTF charter issues

### ISSUE THREAD

**Issue by wseltzer** [w3c/webpayments-ig#44]
A few issues of varying size and scope: 

Team contact % should be TBD

The broadly scoped problem statement and goals feel as though they belong in a whitepaper separate from the charter, similar to the way the [Web of Things charter](http://w3c.github.io/wot/charters/wot-wg-2016.html) refactored to link a [whitepaper](http://w3c.github.io/wot/charters/wot-white-paper-2016.html). This would make clearer what you're asking people to commit, both in legal and vision terms, and what is being shared as context. 

Milestones: 6months from FPWD to CR is probably more optimistic than @plehegar would like to see as Project management.

**Comment by msporny** [comment]
+cc @ianbjacobs @dprophet 

> Team contact % should be TBD

Fixed.

> The broadly scoped problem statement and goals feel as though they belong in a whitepaper separate from the charter

Moved to "Charter Motivations" document and linked to from the proposed charter.

> Milestones: 6months from FPWD to CR is probably more optimistic than @plehegar would like to see as Project management.

Changed FPWD to CR to 9 months.

I also added an "Introduction" section to replace the problem statement and goals section and linked to other relevant/supporting documentation. Also did some general cleanup of the text to make the new charter flow a bit better.

New charter can be viewed here:

http://w3c.github.io/webpayments-ig/VCTF/charter/rc-3.html

Diff-marked copy is here:

http://w3c.github.io/webpayments-ig/VCTF/charter/rc-3-diff.html

W3M-specific landing page for next Wednesday's meeting is here:

http://w3c.github.io/webpayments-ig/VCTF/w3m.html

I think that addresses all of the concerns that you raised. Let me know if you agree/disagree.

**Comment by koalie** [comment]
Hi all,

Hogging Wendy's issue with additional comments as I'm about to send the advance notice to the Members and public via public-new-work, and I just reviewed the draft charter.

Looking at the [current group charter template](https://w3c.github.io/charter-drafts/charter-template.html), please :
- Remove the "Technology and Society Domain" icon
- Move the "Join the $group" link above the table.
- Add to that table the row: "Charter extension [...]"
- Create section 10.1 " Charter History " 

Thanks!

**Comment by msporny** [comment]
Fixed in the current live document, @koalie. We didn't use the charter template you pointed to when putting this particular charter together. Would you prefer that we migrate the content in the current VC charter to the "current group charter template" you point to above? If so, when would you like us to do this?

The main reason that I ask is that it looks like the "Milestones" table has been removed from the new charter (for good reason), and we'd like to follow best practices for this charter as well. Given that the announcement has already gone out, do you want us to create a working draft at a different location and make these updates? Or is it okay to change the live document?

**Comment by koalie** [comment]
Thanks @msporny ! I'm happy.
I'll defer to @wseltzer whether the milestones table stays in or goes out. Indeed, we have removed it from the template as it was not helpful --very few groups followed it.

**Comment by msporny** [comment]
Closing this issue as many of the requested fixes were made, and it's been overcome by events.
